name: 'Update Image Tag'
description: 'Updates Kustomize image tags and creates a PR with the change'
inputs:
  repo:
    description: 'Repository where kustomization.yaml exists'
    required: true
  branch:
    description: 'Branch on the repository in which to apply the changes'
    required: true
    default: "main"
  images:
    description: |
      A multiline, comma delimited string where each line contains two values 1) the directory path to where the kustomization.yaml resides and 2) the image name. This supports multiple image updates in a single change request.

      Example:
        k8s/applications/my-app/production,gcr.io/my-org/my-app
        k8s/applications/my-app/staging,gcr.io/my-org/my-app
    required: true
  tag:
    description: 'Image tag - normally the GitHub SHA'
    required: true
  token:
    description: "GitHub token - a PAT or GitHub App generated token"
    required: true
  source-repo:
    description: 'Source repository for the image that was built'
    required: true
  labels:
    description: 'A comma or newline separated list of labels.'
    required: true
    default: "automerge"
runs:
  using: "composite"
  steps:
    - uses: imranismail/setup-kustomize@v2

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.branch }}
        repository: ${{ inputs.repo }}
        path: infra

    - name: Kustomize
      shell: bash
      run: |
        IFS=$'\n'
        lines="${{ inputs.images }}"
        for line in $lines; do
          IFS=',' read -r path image_name <<< "$line"
          cd ${{ github.workspace }}/infra/${{ inputs.path }}
          kustomize edit set image "$image_name=$image_name":${{ inputs.tag }}
        done

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        path: infra
        token: ${{ inputs.token }}
        delete-branch: true
        branch-suffix: random
        commit-message: Updating ${{ inputs.source-repo }} tag to ${{ inputs.tag }}
        title: "${{ inputs.source-repo }} deployment"
        body: >
            Related to https://github.com/${{ inputs.source-repo }}/commit/${{ inputs.tag }}


            This PR is auto-generated.
        labels: ${{ inputs.labels }}

    - uses: actions/checkout@v3
      with:
        path: ${{ github.repository }}
        fetch-depth: 0
        clean: true
