##
# Label incoming pull requests according to configuration in .github/labeler.yml
##
name: Pull Request Labeler
on:
  - pull_request_target

jobs:
  triage:
    name: Labeler Triage
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
